/*
 * Filter Coefficients (C Source) generated by the Filter Design and Analysis Tool
 * Generated by MATLAB(R) 9.9 and Signal Processing Toolbox 8.5.
 * Generated on: 09-Jun-2021 13:59:21
 */

/*
 * Discrete-Time FIR Filter (real)
 * -------------------------------
 * Filter Structure  : Direct-Form FIR
 * Filter Length     : 202
 * Stable            : Yes
 * Linear Phase      : Yes (Type 2)
 */

/* General type conversion for MATLAB generated C-code  */
/* 
 * Expected path to tmwtypes.h 
 * E:\MATLAB\R2020b\extern\include\tmwtypes.h 
 */
/*
 * Warning - Filter coefficients were truncated to fit specified data type.  
 *   The resulting response may not match generated theoretical response.
 *   Use the Filter Design & Analysis Tool to design accurate
 *   int16 filter coefficients.
 */
const int NL = 202;
const int N[202] = {
        0,      0,      0,     -1,      0,      1,      1,     -1,     -1,
        1,      2,      0,     -3,     -2,      2,      4,     -1,     -5,
       -1,      6,      4,     -5,     -8,      2,     11,      3,    -11,
      -10,      9,     16,     -2,    -20,     -8,     20,     19,    -13,
      -29,      1,     34,     16,    -31,    -34,     19,     48,      2,
      -54,    -29,     47,     56,    -25,    -76,    -10,     81,     51,
      -66,    -91,     30,    117,     24,   -119,    -86,     91,    141,
      -32,   -173,    -50,    169,    139,   -120,   -215,     28,    254,
       94,   -238,   -223,    157,    328,    -14,   -377,   -171,    342,
      365,   -208,   -523,    -22,    593,    326,   -531,   -655,    299,
      948,    125,  -1121,   -757,   1073,   1637,   -625,  -2965,   -812,
     6310,  12913,  12913,   6310,   -812,  -2965,   -625,   1637,   1073,
     -757,  -1121,    125,    948,    299,   -655,   -531,    326,    593,
      -22,   -523,   -208,    365,    342,   -171,   -377,    -14,    328,
      157,   -223,   -238,     94,    254,     28,   -215,   -120,    139,
      169,    -50,   -173,    -32,    141,     91,    -86,   -119,     24,
      117,     30,    -91,    -66,     51,     81,    -10,    -76,    -25,
       56,     47,    -29,    -54,      2,     48,     19,    -34,    -31,
       16,     34,      1,    -29,    -13,     19,     20,     -8,    -20,
       -2,     16,      9,    -10,    -11,      3,     11,      2,     -8,
       -5,      4,      6,     -1,     -5,     -1,      4,      2,     -2,
       -3,      0,      2,      1,     -1,     -1,      1,      1,      0,
       -1,      0,      0,      0
};
